ccuffs/cc.uffs.edu.br

_pages/grade.md

Encontrei dois pequenos erros de digitação. Apenas um ajuste na tag h2.

Ajuste html: 'grade bacharelado' e 'vespertino' para 'noturno'

---

_pages/grade.md

Coloquei toda a grade noturna, mas como elas são longas, poderia ter tabs para diferenciar o noturno e o vespertino. Estava pensando sobre as optativas, podemos colocar as optativas em outra pagina.

Adicionando Grade Noturno Completa

---

_pages/ca.md

Foi adicionada a URL do grupo do telegram, sugerido pelo @Dovyski .  Em breve teremos o  buzzfeed da computação que ainda está em construção.

URL do telegram atualizada

---

_pages/ensino-monitoria.md

closes #42 
- As informações sobre a monitoria de Algoritmos e Programação foram atualizadas (nome e contato dos monitores);
- Foi adicionado um aviso sobre a monitoria de CD e Hardware, notificando sobre a (triste) falta de monitores;
- Para a monitoria de Cálculo foram apenas removidas as informações obsoletas. Entrei em contato com o professor Milton por e-mail, se ele me responder até terça-feira atualizo as informações. Até lá, manterei esta PR como rascunho. Se até terça não houver uma resposta, farei as correções necessárias e podemos prosseguir com o merge. Neste caso as informações serão atualizadas posteriormente.

Corrige informações sobre monitoria

---

CHANGELOG.md
CODE-OF-CONDUCT.md
CONTRIBUTING.md
ROADMAP.md

closes #40
Esta PR adiciona os seguintes arquivos:
- `CONTRIBUTING.md` - como descrito em #40;
- `CHANGELOG.md` - como descrito em #40;
- `ROADMAP.md`;
- `CODE-OF-CONDUCT.md`;
Os dois últimos arquivos eu notei que também estavam faltantes, e eram referenciados em `CONTRIBUTING.md`. Em suma, todos os arquivos inseridos são provenientes do template do curso, sem alteração nenhuma, exceto para `CONTRIBUTING.md`, que apresenta algumas informações adaptadas para este projeto.

Adiciona arquivos faltantes

---

_pages/turmas/2020.md

adicionado 'eu'

---

_pages/turmas/2020.md

Foi incluso no site, informações como: Link página pessoal e conta do GitHub.

Inclusão de informações

---

_pages/turmas/2020.md

Add nome a lista, e nome da aba para "Turma 2020.2"

Add discente "Tiago de Macedo" à lista

---

_pages/turmas/2020.md

me adicionaaaaa

---

_pages/turmas/2020.md

Ainda pendente link para o site, professor, lembre de cobrar na semana que vem <3

Inserção de Nome e site pessoal

---

_pages/turmas/2020.md

ALteração Nome

---

_pages/turmas/2020.md

Ajustei no final dos links cc.uffs.edu.br/pessoa/NOME adicionando uma barra no final, para não dar erro do nginx

ERROS NOS LINKS -> PRECISA DE /

---

_pages/turmas/2020.md

acho que agora foi kk

---

_pages/ensino-monitoria.md

NOVO HORARIO DE MONITORIA DE ALGORITMOS 2021.2

NOVO HORARIO DE MONITORIA DE ALGORITMOS 2021.2

---

404/index.html

Outro pull request, apenas com a  pagina de erro 404

erro 404 melhorado

---

_pages/turmas/2020-2.md

Ordenado e padronizado dados da turma 2020-2

---

_posts/noticias/2022-08-30-datas-2022-2.md

Dbguilherme patch 1

---

_data/faq.yml

Solves the https://github.com/ccuffs/cc.uffs.edu.br/issues/125 issue.

Fix faq.yml syntax

---

_includes/page-meta.html
_includes/post-grid.html
_includes/post-meta-inline.html
_includes/post-meta.html
_layouts/default.html
_layouts/post.html

Solves the https://github.com/ccuffs/cc.uffs.edu.br/issues/109 issue.

Adjust dates to the brazilian format

---

_posts/postagens/2025-04-25-validacao-acc-por-trabalho.md

Adiciona guia passo a passo para validação de ACCs por experiência profissional.

docs: adiciona página de instruções para validação de ACCs por trabalho
